name: Test

on:
  workflow_run:
    workflows:
      - Pre flight
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
        echo "$GITHUB_CONTEXT"
