name: Test

on:
  workflow_run:
    workflows:
      - Pre flight
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo ${{ github }}
