name: cypress

on:
  workflow_run:
    workflows:
      - cypress filter
    types:
      - completed

jobs:
  test-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
